#Filename: dev.yml
version: '3.7'
services:
    web:
        command: npm start
        build:
            context: .
            dockerfile: Dockerfile-development
        ports:
            - 3000:3000
        environment:
            - REACT_APP_NODE_ENV=development
            - REACT_APP_API_URL=http://localhost:8000/api