#Filename: Dockerfile
FROM node:12.11 as apartame-front
LABEL maintainer="christianahvilla@gmail.com"
ENV NPM_CONFIG_LOGLEVEL warn
# Create a work directory and copy over our dependency manifest files.
RUN mkdir /app
WORKDIR /app
COPY /src /app/src
COPY ["package.json", "package-lock.json*", "./"]
RUN npm install
#Expose Port 3000 since this is our dev environment
EXPOSE 3000