const categoryConstants = {
    UPDATE_CATEGORY_BEGIN: 'UPDATE_CATEGORY_BEGIN',
    UPDATE_CATEGORY_SUCCESS: 'UPDATE_CATEGORY_SUCCESS',
    UPDATE_CATEGORY_ERROR: 'UPDATE_CATEGORY_ERROR',

    FETCH_CATEGORY_BEGIN: 'FETCH_CATEGORY_BEGIN',
    FETCH_CATEGORY_SUCCESS: 'FETCH_CATEGORY_SUCCESS',
    FETCH_CATEGORY_ERROR: 'FETCH_CATEGORY_ERROR',

    SAVE_CATEGORY_BEGIN: 'SAVE_CATEGORY_BEGIN',
    SAVE_CATEGORY_SUCCESS: 'SAVE_CATEGORY_SUCCESS',
    SAVE_CATEGORY_ERROR: 'SAVE_CATEGORY_ERROR',

    DELETE_CATEGORY_BEGIN: 'DELETE_CATEGORY_BEGIN',
    DELETE_CATEGORY_SUCCESS: 'DELETE_CATEGORY_SUCCESS',
    DELETE_CATEGORY_ERROR: 'DELETE_CATEGORY_ERROR',
};

export default categoryConstants;
