const imageConstants = {
    SAVE_IMAGE_BEGIN: 'SAVE_IMAGE_BEGIN',
    SAVE_IMAGE_SUCCESS: 'SAVE_IMAGE_SUCCESS',
    SAVE_IMAGE_ERROR: 'SAVE_IMAGE_ERROR',

    DELETE_IMAGE_BEGIN: 'DELETE_IMAGE_BEGIN',
    DELETE_IMAGE_SUCCESS: 'DELETE_IMAGE_SUCCESS',
    DELETE_IMAGE_ERROR: 'DELETE_IMAGE_ERROR',
};

export default imageConstants;
