const shopConstants = {
    UPDATE_SHOP_BEGIN: 'UPDATE_SHOP_BEGIN',
    UPDATE_SHOP_SUCCESS: 'UPDATE_SHOP_SUCCESS',
    UPDATE_SHOP_ERROR: 'UPDATE_SHOP_ERROR',

    FETCH_SHOP_BEGIN: 'FETCH_SHOP_BEGIN',
    FETCH_SHOP_SUCCESS: 'FETCH_SHOP_SUCCESS',
    FETCH_SHOP_ERROR: 'FETCH_SHOP_ERROR',

    SAVE_SHOP_BEGIN: 'SAVE_SHOP_BEGIN',
    SAVE_SHOP_SUCCESS: 'SAVE_SHOP_SUCCESS',
    SAVE_SHOP_ERROR: 'SAVE_SHOP_ERROR',

    DELETE_SHOP_BEGIN: 'DELETE_SHOP_BEGIN',
    DELETE_SHOP_SUCCESS: 'DELETE_SHOP_SUCCESS',
    DELETE_SHOP_ERROR: 'DELETE_SHOP_ERROR',
};

export default shopConstants;
