const userConstants = {
    UPDATE_USER_BEGIN: 'UPDATE_USER_BEGIN',
    UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
    UPDATE_USER_ERROR: 'UPDATE_USER_ERROR',

    FETCH_USER_BEGIN: 'FETCH_USER_BEGIN',
    FETCH_USER_SUCCESS: 'FETCH_USER_SUCCESS',
    FETCH_USER_ERROR: 'FETCH_USER_ERROR',

    SAVE_USER_BEGIN: 'SAVE_USER_BEGIN',
    SAVE_USER_SUCCESS: 'SAVE_USER_SUCCESS',
    SAVE_USER_ERROR: 'SAVE_USER_ERROR',

    DELETE_USER_BEGIN: 'DELETE_USER_BEGIN',
    DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
    DELETE_USER_ERROR: 'DELETE_USER_ERROR',
};

export default userConstants;
